### ISSUE TITLE
A mistake in function--build_graph_structure

### ISSUE THREAD

**Issue by JR9124** [loicland/point-cloud-regularization#5]
Hi, I have read the code of build_graph_structure in detail, and I think that there is a mistake in the function(line 48). As matlab indexes a matrix in a column-first way, and the variable (neighbors) was transformed in line 40 when building target nodes, I think the variable (edge_weight) should also be transformed, or it is not the right edge weight for corresponding source to target nodes. I performed several experiments by using my data, and I found that after edge_weight being transformed, the accuracy was also increased. Am I right? Could you check the codes and reply me?Thank you!

**Comment by loicland** [comment]
You are correct! Thanks for pointing it out.
